# Generated by Django 4.2.24 on 2025-09-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='ai_player',
            field=models.CharField(default='O', max_length=1),
        ),
    ]
