# Generated by Django 4.2.24 on 2025-09-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_ai_enabled_game_ai_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ai_difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='HARD', max_length=6),
        ),
    ]
